### ISSUE TITLE
0C4 trying to run exec in batch

### ISSUE THREAD

**Issue by NicClouston** [mvslovers/brexx370#67] opened 2020-09-29 11:32 UTC
Having (un)successfully run this code in batch I put a trace in to try and find out why it was not working as exepected. The initial run threw up a problem created in my conversion from EXCIO on z/OS to the EXECIO provided with BREXX370. I corrected the problem (wrong variable name) and evresince then, any attempt to run has ended up with an 0C4. I tried running the installation tests again and they all worked.

Here is the JCL I use:
```
//N13964A0 JOB (NICC),AUTOSUB,MSGCLASS=X,CLASS=A,NOTIFY=N13964
//*                                                           
//SETRC   EXEC PGM=GPSETRC,PARM=0000                          
//STEPLIB  DD DSN=N13964.LOAD,                                
//            DISP=SHR                                        
//         DD DSN=SYSC.PL1LIB,                                
//            DISP=SHR                                        
//SYSPRINT DD SYSOUT=*                                        
//SYSUDUMP DD SYSOUT=*                                        
//PLIDUMP  DD SYSOUT=*                                        
//*                                                           
//NEXTJOB EXEC RXBATCH,                                       
//         BREXX='BREXX',                                     
//         REGION=7168K,                                      
//         EXEC='DJC',                                        
//         P='AUTOSUB',                                       
//         SLIB='N13964.EXEC',                                
//         COND=(0,NE,SETRC)                                  
//PLAN     DD DSN=N13964.CNTL(AUTODJC),DISP=SHR               
//SYSUDUMP DD SYSOUT=*                                        
//SYSDUMP  DD SYSOUT=*                                        
//SYSTSPRT DD SYSOUT=*                                        
//SYSPRINT DD SYSOUT=*                                        
//
```
and this is the code
```rexx
/*- Rexx ------------------------------------------------------------*/ 
/*------------------------------------------------------------ Rexx -*/ 
Trace R                                                                 
Say "        Dependent xxx Control (XXX) starting"                      
Signal On Syntax Name ohShit                                            
                                                                        
Arg this_job                                                            
                                                                        
NOT_OK = 28                                                             
OK     = 0                                                              
                                                                        
Say "XXX000: Job executing XXX is "this_job                             
                                                                        
"EXECIO * DISKR PLAN(STEM xxxrec."                                      
If rc <> OK                                                             
Then Do                                                                 
   Say "EXECIO gave RC = "rc                                            
   Exit NOT_OK                                                          
End                                                                     
                                                                        
Do ix = 1 To xxxrec.0                                                   
                                                                        
   If Substr(xxxrec.ix,1,1) ¬= '#'                                      
   Then Do                                                              
                                                                        
      Parse Var xxxrec.ix job hold_count rest                           
      Parse Var rest predecessor pre_s                                  
                                                                        
      Do While predecessor ¬= ''                                        
                                                                        
         predecessor = Strip(predecessor,'B',' ')                       
         If predecessor = this_job                                      
         Then Do                                                        
                                                                        
            hold_count = hold_count - 1                                 
            If hold_count = 0                                           
            Then Do                                                     
                                                                        
               sysdsn_msg = Sysdsn("'"job"'")                           
               If sysdsn_msg = 'OK',                                    
               Then "SUBMIT '"job"'"                                   
               Else Do                                                 
                  Say 'XXX001S: INVALID NEXT JOB - 'job                
                  Say 'XXX002S: 'sysdsn_msg                            
                  Return NOT_OK                                        
               End                                                     
                                                                       
            End                                                        
                                                                       
         End                                                           
                                                                       
         Parse Var pre_s predecessor pre_s                             
                                                                       
      End                                                              
                                                                       
      xxxrec.ix = job hold_count rest                                  
                                                                       
   End                                                                 
                                                                       
End                                                                    
                                                                       
"EXECIO * DISKW PLAN(STEM xxxrec."                                     
                                                                       
If xxxrec.0 = 0                                                        
Then Do                                                                
                                                                       
   Say 'XXX001E: NO DATA RECORDS READ'                                 
   Return 16                                                           
                                                                       
End                                                                    
                                                                       
Exit                                                                   
/*===================================================================*/
ohShit:                                                                
/*-------------------------------------------------------------------*/
/* Rexx Error routine. Called on Syntax error. Issue error details & */
/* terminate the script with the return code.                        */
/*-------------------------------------------------------------------*/
_errorrc = rc                                                          
Parse source . . _exec .                                               
Say 'An error has been encountered in '||_exec 
Say 'Return code is: ' _errorrc                             
Say 'The line of code in question is:' Sourceline(Sigl)'.'  
Say Errortext(_errorrc)                                     
Say ' '                                                     
Exit rc 
```
I attach the output 
[autosub_prt00e.txt](https://github.com/mvslovers/brexx370/files/5298619/autosub_prt00e.txt)

**Comment by Peter-Jacob** [comment] 2020-09-29 11:52
Hi Nic, 

 

For better testing, can you please send me the contents of the file N13964.CNTL(AUTODJC)? In my BREXX version it runs, but of course fails in reading the data.

 

Ty

 

Peter

 

Von: NicClouston <notifications@github.com> 
Gesendet: Dienstag, 29. September 2020 13:33
An: mvslovers/brexx370 <brexx370@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [mvslovers/brexx370] 0C4 trying to run exec in batch (#67)

 

Having (un)successfully run this code in batch I put a trace in to try and find out why it was not working as exepected. The initial run threw up a problem created in my conversion from EXCIO on z/OS to the EXECIO provided with BREXX370. I corrected the problem (wrong variable name) and evresince then, any attempt to run has ended up with an 0C4. I tried running the installation tests again and they all worked.

Here is the JCL I use:
//N13964A0 JOB (NICC),AUTOSUB,MSGCLASS=X,CLASS=A,NOTIFY=N13964 //* //SETRC EXEC PGM=GPSETRC,PARM=0000 //STEPLIB DD DSN=N13964.LOAD, // DISP=SHR // DD DSN=SYSC.PL1LIB, // DISP=SHR //SYSPRINT DD SYSOUT=* //SYSUDUMP DD SYSOUT=* //PLIDUMP DD SYSOUT=* //* //NEXTJOB EXEC RXBATCH, // BREXX='BREXX', // REGION=7168K, // EXEC='DJC', // P='AUTOSUB', // SLIB='N13964.EXEC', // COND=(0,NE,SETRC) //PLAN DD DSN=N13964.CNTL(AUTODJC),DISP=SHR //SYSUDUMP DD SYSOUT=* //SYSDUMP DD SYSOUT=* //SYSTSPRT DD SYSOUT=* //SYSPRINT DD SYSOUT=* //
and this is the code
`/- Rexx ------------------------------------------------------------/
/------------------------------------------------------------ Rexx -/
Trace R
Say " Dependent xxx Control (XXX) starting"
Signal On Syntax Name ohShit

Arg this_job

NOT_OK = 28
OK = 0

Say "XXX000: Job executing XXX is "this_job

"EXECIO * DISKR PLAN(STEM xxxrec."
If rc <> OK
Then Do
Say "EXECIO gave RC = "rc
Exit NOT_OK
End

Do ix = 1 To xxxrec.0

If Substr(xxxrec.ix,1,1) ¬= '#'
Then Do

  Parse Var xxxrec.ix job hold_count rest                           
 
  Parse Var rest predecessor pre_s                                  
 
                                                                    
 
  Do While predecessor ¬= ''                                        
 
                                                                    
 
     predecessor = Strip(predecessor,'B',' ')                       
 
     If predecessor = this_job                                      
 
     Then Do                                                        
 
                                                                    
 
        hold_count = hold_count - 1                                 
 
        If hold_count = 0                                           
 
        Then Do                                                     
 
                                                                    
 
           sysdsn_msg = Sysdsn("'"job"'")                           
 
           If sysdsn_msg = 'OK',                                    
 
           Then "SUBMIT '"job"'"                                   
 
           Else Do                                                 
 
              Say 'XXX001S: INVALID NEXT JOB - 'job                
 
              Say 'XXX002S: 'sysdsn_msg                            
 
              Return NOT_OK                                        
 
           End                                                     
 
                                                                   
 
        End                                                        
 
                                                                   
 
     End                                                           
 
                                                                   
 
     Parse Var pre_s predecessor pre_s                             
 
                                                                   
 
  End                                                              
 
                                                                   
 
  xxxrec.ix = job hold_count rest                                  
 

End

End

"EXECIO * DISKW PLAN(STEM xxxrec."

If xxxrec.0 = 0
Then Do

Say 'XXX001E: NO DATA RECORDS READ'
Return 16

End

Exit
/===================================================================/
ohShit:
/-------------------------------------------------------------------/
/* Rexx Error routine. Called on Syntax error. Issue error details & /
/ terminate the script with the return code. /
/-------------------------------------------------------------------*/
_errorrc = rc
Parse source . . _exec .
Say 'An error has been encountered in '||_exec
Say 'Return code is: ' _errorrc
Say 'The line of code in question is:' Sourceline(Sigl)'.'
Say Errortext(_errorrc)
Say ' '
Exit rc `
I attach the output
autosub_prt00e.txt <https://github.com/mvslovers/brexx370/files/5298619/autosub_prt00e.txt>

**Comment by NicClouston** [comment] 2020-09-29 12:23
Hi Peter
Thank you for looking at this.These are the contents of that dataset:# THIS IS THE SAMPLE JOB FLOW FOR THE AUTOSUB FACILITY
#                                                     
N13964.CNTL(AUTOSUB1) 1 AUTOSUB                       
N13964.CNTL(AUTOSUB2) 1 AUTOSUB1                      
N13964.CNTL(AUTOSUB3) 1 AUTOSUB1                      
N13964.CNTL(AUTOSUB4) 2 AUTOSUB2 AUTOSUB3             
#                                                     
#              AUTOSUB                                
#                 ¦                                   
#              AUTOSUB1                               
#                 ¦                                   
#            _____¦____                               
#            ¦        ¦                               
#         AUTOSUB2 AUTOSUB3                           
#            ¦        ¦                               
#            -----+----                               
#                 ¦                                   
#              AUTOSUB4                               
#                                                     

This dataset is FB 80 although in reality it could be VB, or a longer LRECL as the list of predecessors (the 3rd field) is not limited. I have always tested with the above jobstream.

I forgot to mention in my post the fact that I get nothing at all from the trace so it is either ignoring the trace or choking at, or before that point.

Regards 
Nic

**Comment by Peter-Jacob** [comment] 2020-09-29 17:04
Hi Nic, 

 

I ran your exec with this data:

 

# THIS IS THE SAMPLE JOB FLOW FOR THE AUTOSUB FACILITY  

#                                                       

MS.MSPDM.CNTL(AUTOSUB1) 1  AUTOSUB                      

MS.MSPDM.CNTL(AUTOSUB2) 1 AUTOSUB1                      

MS.MSPDM.CNTL(AUTOSUB3) 1 AUTOSUB1                      

MS.MSPDM.CNTL(AUTOSUB4) 2 AUTOSUB2 AUTOSUB3             

#                                                       

#              AUTOSUB                                  

#                 ¦                                     

#              AUTOSUB1                                 

#                 ¦                                     

#            _____¦____                                 

#            ¦        ¦                                 

#         AUTOSUB2 AUTOSUB3                             

#            ¦        ¦                                 

#            -----+----                                 

#                 ¦                                     

#              AUTOSUB4                                 

#                                                       

The CNTLs contain only a IEFBR14 call.

 

The output is:

 

Dependent xxx Control (XXX) starting                 

XXX000: Job executing XXX is AUTOSUB                  

$HASP165 JOB 6481  PEJ1NIX ENDED- MAX COND CODE 0000  

 

So the job was submitted,  and the data file was updated:

 

# THIS IS THE SAMPLE JOB FLOW FOR THE AUTOSUB FACILITY  

#                                                       

MS.MSPDM.CNTL(AUTOSUB1) 0 AUTOSUB                       

MS.MSPDM.CNTL(AUTOSUB2) 1 AUTOSUB1                      

MS.MSPDM.CNTL(AUTOSUB3) 1 AUTOSUB1                      

MS.MSPDM.CNTL(AUTOSUB4) 2 AUTOSUB2 AUTOSUB3             

…

…

 

No 0C4 occurred!

 

If you wish, I can cut you a new beta release of BREXX V2R3M0 tomorrow, and you try it with the new release.

 

Let me think what you think about it.

 

Regards

 

Peter 

 

Von: NicClouston <notifications@github.com> 
Gesendet: Dienstag, 29. September 2020 14:24
An: mvslovers/brexx370 <brexx370@noreply.github.com>
Cc: Peter-Jacob <PeterJ88@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [mvslovers/brexx370] 0C4 trying to run exec in batch (#67)

 

Hi Peter
Thank you for looking at this.These are the contents of that dataset:# THIS IS THE SAMPLE JOB FLOW FOR THE AUTOSUB FACILITY
#                                                     
N13964.CNTL(AUTOSUB1) 1 AUTOSUB                       
N13964.CNTL(AUTOSUB2) 1 AUTOSUB1                      
N13964.CNTL(AUTOSUB3) 1 AUTOSUB1                      
N13964.CNTL(AUTOSUB4) 2 AUTOSUB2 AUTOSUB3             
#                                                     
#              AUTOSUB                                
#                 ¦                                   
#              AUTOSUB1                               
#                 ¦                                   
#            _____¦____                               
#            ¦        ¦                               
#         AUTOSUB2 AUTOSUB3                           
#            ¦        ¦                               
#            -----+----                               
#                 ¦                                   
#              AUTOSUB4                               
#                                                     

This dataset is FB 80 although in reality it could be VB, or a longer LRECL as the list of predecessors (the 3rd field) is not limited. I have always tested with the above jobstream.

I forgot to mention in my post the fact that I get nothing at all from the trace so it is either ignoring the trace or choking at, or before that point.

Regards 
Nic

**Comment by NicClouston** [comment] 2020-09-29 18:23
Hi Peter
OK - I assume some corruption at my end  so I will reinstall BRexx. No need to send me a new install unless it has an improved EXECIO. The original version of this program used OPEN and FINIS and read 1 record at a time and rewrote updated records. The documentation is severely lacking in return codes that can be expected (this is throughout the documentation for BRexx not just BRexx370).
 
 I will start re-isntalling tomorrow.
RegardsNic
 
-----Original Message-----

**Comment by mainframed** [comment] 2020-09-29 23:42
For the record you can post code in code blocks with syntax highlighting with ` ``` `
For example this:

~~~
```rexx
say 'some rexx code'
```
~~~

becomes:

```rexx
say 'some rexx code'
```

For example (jcl):

```jcl
//N13964A0 JOB (NICC),AUTOSUB,MSGCLASS=X,CLASS=A,NOTIFY=N13964 
//* 
//SETRC EXEC PGM=GPSETRC,PARM=0000 
//STEPLIB DD DSN=N13964.LOAD, 
// DISP=SHR 
// DD DSN=SYSC.PL1LIB, 
// DISP=SHR 
//SYSPRINT DD SYSOUT=* 
//SYSUDUMP DD SYSOUT=* 
//PLIDUMP DD SYSOUT=* 
//* 
//NEXTJOB EXEC RXBATCH, 
// BREXX='BREXX', 
// REGION=7168K, 
// EXEC='DJC', 
// P='AUTOSUB', 
// SLIB='N13964.EXEC', 
// COND=(0,NE,SETRC) 
//PLAN DD DSN=N13964.CNTL(AUTODJC),DISP=SHR 
//SYSUDUMP DD SYSOUT=* 
//SYSDUMP DD SYSOUT=* 
//SYSTSPRT DD SYSOUT=* 
//SYSPRINT DD SYSOUT=* 
//
```

and rexx:

```rexx
/- Rexx ------------------------------------------------------------/
/------------------------------------------------------------ Rexx -/
Trace R
Say " Dependent xxx Control (XXX) starting"
Signal On Syntax Name ohShit
Arg this_job
NOT_OK = 28
OK = 0
Say "XXX000: Job executing XXX is "this_job
"EXECIO * DISKR PLAN(STEM xxxrec."
If rc <> OK
Then Do
Say "EXECIO gave RC = "rc
Exit NOT_OK
End
Do ix = 1 To xxxrec.0
If Substr(xxxrec.ix,1,1) ¬= '#'
Then Do
  Parse Var xxxrec.ix job hold_count rest
  Parse Var rest predecessor pre_s
  Do While predecessor ¬= ''
     predecessor = Strip(predecessor,'B',' ')
     If predecessor = this_job
     Then Do
        hold_count = hold_count - 1
        If hold_count = 0
        Then Do
           sysdsn_msg = Sysdsn("'"job"'")
           If sysdsn_msg = 'OK',
           Then "SUBMIT '"job"'"
           Else Do
              Say 'XXX001S: INVALID NEXT JOB - 'job
              Say 'XXX002S: 'sysdsn_msg
              Return NOT_OK
           End
        End
     End
     Parse Var pre_s predecessor pre_s
  End
  xxxrec.ix = job hold_count rest
End
End
"EXECIO * DISKW PLAN(STEM xxxrec."
If xxxrec.0 = 0
Then Do
Say 'XXX001E: NO DATA RECORDS READ'
Return 16
End
Exit
/===================================================================/
ohShit:
/-------------------------------------------------------------------/
/* Rexx Error routine. Called on Syntax error. Issue error details & /
/ terminate the script with the return code. /
/-------------------------------------------------------------------*/
_errorrc = rc
Parse source . . _exec .
Say 'An error has been encountered in '||_exec
Say 'Return code is: ' _errorrc
Say 'The line of code in question is:' Sourceline(Sigl)'.'
Say Errortext(_errorrc)
Say ' '
Exit rc `
```

**Comment by NicClouston** [comment] 2020-10-01 10:49
On further testing I find that the error is caused by the line
```Then "SUBMIT '"job"'"```
Changing this to ADDRESS TSO 'submit...' got rid of the 0C4 but resulted in a return code of -1 and no messages. The documentation fails to say what the correct format of the command is or the environment to be addressed. In fact, when I display the environment 
```SAY ADDRESS()```
 I get SYSTEM as the result. When I use SYSTEM in my submit code I get a -1 as well.

when I get the 0C4 either it happens before my code starts to be interpreted or the error routine manages to wipe out anything already sent to STDOUT and STDERR.

**Comment by mgrossmann** [comment] 2020-10-01 13:24
I'm not quite sure I understand your problem. If you call the TSO command `SUBMIT`,
of course, it only works in a TSO environment. 
That's why you have to execute an `ADDRESS TSO`. 
BREXX recognizes if it was called from TSO. Then `ADDRESS()` is automatically set to TSO, 
otherwise to SYSTEM.
```
 READY            
rx - say ADDRESS()
 TSO              
 READY  
```

Why SUBMIT returns a -1, we'll have a look at.

Can you support us with sending us a shortened but woking rexx script?

Ty Mike

**Comment by mgrossmann** [comment] 2020-11-27 12:37
Hello @NicClouston 

can you give me an update on this topic?

Regards Mike

**Comment by NicClouston** [comment] 2020-11-27 13:55
Hi Mike
As requested I posted a minimum code example, some time ago. I have not been using Herculees/MVS 3.8 since then concentrating on an 'include' process for my Windows 10 oorexx and using builtin ANSI codes for colours on the same platform.
RegardsNic
 
-----Original Message-----

**Comment by mgrossmann** [comment] 2020-11-27 15:43
Hi @NicClouston 

regarding your issues with calling the TSO SUBMIT command.
I'm not able to reproduce this at our end.

```rexx
/* BREXX/370             
   ISSUE #67 */          
                         
ADDRESS TSO              
"SUBMIT 'MIG.CNTL(BR14)'"
                         
SAY "RC="RC              
```

This REXX script is finishing fine with RC(0).

```
 READY                       
rx #67                       
 JOB BR14(JOB07427) SUBMITTED
 RC=0                        
 READY                       
```

I will close this issue. In case you will continue your work later, 
feel free to create a new issue. Have fun with your new stuff.

Mike

**Closed by mgrossmann** 2020-11-27 15:43 UTC
